---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: assignments.shaper.amahdha.com
spec:
  group: shaper.amahdha.com
  names:
    kind: Assignment
    listKind: AssignmentList
    plural: assignments
    singular: assignment
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Assignment is the Schema for the assignments API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: AssignmentSpec defines the desired state of Assignment
            properties:
              isDefault:
                description: IsDefault is true if this assignment is the default assignment.
                type: boolean
              profileName:
                description: ProfileName is the name of the profile to assign to the
                  machine.
                type: string
              subjectSelectors:
                description: SubjectSelectors is a map of selectors that are used
                  to match a machine.
                properties:
                  buildarch:
                    description: BuildarchList is a list of build architectures to
                      match.
                    items:
                      description: Buildarch is the build architecture of the machine.
                      type: string
                    type: array
                  uuidList:
                    description: UUIDList is a list of UUIDs to match.
                    items:
                      type: string
                    type: array
                required:
                - buildarch
                - uuidList
                type: object
            required:
            - isDefault
            - profileName
            - subjectSelectors
            type: object
          status:
            description: AssignmentStatus defines the observed state of Assignment
            type: object
        type: object
    served: true
    storage: true
